### ISSUE TITLE
Assistance debugging?

### ISSUE THREAD

**Issue by rachelmh** [DavidArmstrong/SCL3300#23]
Hi David,

I wasn't sure how to contact you other than through this method. I have tried using this library with both an Arduino Uno and Mega and neither seem to be working. Perhaps it is an issue with my wiring? I followed the wiring suggestions from here: https://www.mouser.com/datasheet/2/281/pcbspec_scx3300-1568230.pdf

and am using a sparkfun bi-directional level shifter as you recommended.  Here is my current wiring  diagram:

(Lo--Hi) is the bi directional level shifter.

On the left half of the chip I have:
AVSS-GND                                   
XReset -                                      
INT -                                            
CLK 0
DVDD- +3.3V
DVSS - GND
DVSS - GND
NC - 

On the right half of the chip I have
AVSS- GND
AVDD - +3.3V
CSB  -  Lo--Hi--Pin D10 Uno
         |
        5kOhm
         |
       +3.3V

MISO- Lo--Hi -- Pin D12 Uno

MOSI- Lo--Hi--Pin D11 Uno

SCK - Lo--Hi-- Pin D13 Uno

NC-

If you have any suggestions I would greatly appreciate it! Please feel free to email me at rachelmh@mit.edu

**Comment by DavidArmstrong** [comment]
Replied in private email, and explained how to get debugging output.

**Comment by DavidArmstrong** [comment]
Initial issue was resolved offline long ago.  So closing this issue.
