### ISSUE TITLE
Inclinometer Throws Error when Shaken

### ISSUE THREAD

**Issue by sachinthaLUT** [DavidArmstrong/SCL3300#38]
Hello,

I'm using the SCL3300 on a custom PCB alongside the Arduino Nano ESP32. 

I've checked that the PCB connections and confirmed that they are stable. However, the program keeps on returning "Inclinometer error detected..." sometimes when the inclinometer is moved or shaken. I can't figure out why. Help is appreciated :)'.

I've also noticed that the error keeps occurring when the inclinometer is held at specific angles. In most of the other angles the error comes and goes.

A screenshot from the custom PCB related to the inclionometer is provided below.

![image](https://github.com/user-attachments/assets/8fd17564-7833-4686-8178-890e6f3664ef)

A typical output taken from the serial monitor is given below.

![image](https://github.com/user-attachments/assets/2b713bda-84d9-4ac0-8e10-01127f4eaba6)

The code is given below.

```/* Alternate SPI interface used to Read Tilt angles from Murata SCL3300 Inclinometer
 * Version 3.3.0 - September 13, 2021
 * Example9_AlternateSPI
*/

#include <SPI.h>
#include <SCL3300.h>

SCL3300 inclinometer;


void setup() {
  Serial.begin(9600);

  pinMode(D7, INPUT_PULLUP);

  delay(2000); //SAMD boards may need a long time to init SerialUSB
  Serial.println("Define a specific SPI interface for the SCL3300 Inclinometer");

  // Change the begin() parameters here, as needed, to reference the SPI
  // interface being used for the SCL3300 inclinometer.
  // The default Arduino interface is "SPI", and is shown here
  if (inclinometer.begin(SPI, 3) == false) {
    Serial.println("Murata SCL3300 inclinometer not connected.");
    while(1); //Freeze
  } else
    Serial.println("Murata SCL3300 inclinometer is connected.");
}

void loop() {
  if (inclinometer.isConnected()) {
    Serial.println("Inclinometer is still alive...");
  } else {
    Serial.println("Inclinometer error detected...");
  }
  if (inclinometer.available()) { //Get next block of data from sensor
    Serial.println(inclinometer.getCalculatedAngleX());
    Serial.println(inclinometer.getCalculatedAngleY());
    Serial.println(inclinometer.getCalculatedAngleZ());
    Serial.println(inclinometer.getCalculatedAccelerometerX());
    Serial.println(inclinometer.getCalculatedAccelerometerY());
    Serial.println(inclinometer.getCalculatedAccelerometerZ());
    Serial.println(inclinometer.getCalculatedTemperatureCelsius());
    Serial.println();
    delay(150);
  } else inclinometer.reset();
}```

**Comment by DavidArmstrong** [comment]
Keep in mind that the default mode for the SCL3300 is mode 4.  Mode 4 is limited to +-10 degrees to level for accurate readings.  

Shaking the sensor is definitely causing accelerations outside of that range, which is expected to cause errors.  Movements should be slow, as the sensor is using the acceleration of gravity to determine the angle difference from level. Fast movements are going to add an additional acceleration vector to the measurement.

If the sensor needs to be able to measure an arbitrary angle, then the library needs to set the SCL3300 in mode 1 or 2.  See the Example10_Mode1 sketch on how to set and use a different mode for the sensor.

**Comment by sachinthaLUT** [comment]
Hi Dave,

Thank you very much for the prompt response!. Your solution worked!. It was an oversight from my end in selecting this chip because I assumed it would read angles from 0-360 degrees with the same level of accuracy.

Sachintha.
